name: Staging Release

on:
  push:
    branches:
      - staging

jobs:
  release:
    name: Create Prerelease Version PR
    runs-on: ubuntu-latest
    # Skip if the push is from the changeset action (to prevent infinite loops)
    if: ${{ !contains(github.event.head_commit.message, 'Version packages') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Enter Prerelease Mode
        run: npx changeset pre enter rc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
          title: 'Release Candidate Version Packages'
          commit: 'Version packages (rc)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}